---@class Glyph
---@field label string
---@field text string
---@field text_edit string

local url = "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/glyphnames.json"
local tmp = "/tmp/glyphs.json"
local output_file = "lua/blink-cmp-nerdfont/glyphs.lua"

local json = require("dkjson")

---@param source string
---@param destination string
local function download_file(source, destination)
    local ok = os.execute(string.format("curl --silent --output %s '%s'", destination, source))
    if not ok then
        error("Failed to download: " .. source)
    end
end

---@param path string
---@return Glyph[]
local function parse(path)
    local glyph_file = io.open(path, "r")
    if not glyph_file then
        error("Failed to open file: " .. path)
    end

    local content = glyph_file:read("*a")
    glyph_file:close()

    local data = json.decode(content)

    ---@type Glyph[]
    local glyphs = {}
    for key, value in pairs(data) do
        if key ~= "METADATA" then
            local char = value.char
            local label = ":" .. key .. ":"
            table.insert(glyphs, {
                label = char .. " " .. label,
                text = char,
                text_edit = label,
            })
        end
    end

    table.sort(glyphs, function(a, b) return a.text_edit < b.text_edit end)
    return glyphs
end

---@param glyphs Glyph[]
---@param path string
local function write_lua(glyphs, path)
    local out_file = io.open(path, "w")
    if not out_file then
        error("Failed to open output file: " .. path)
    end

    out_file:write("-- Auto-generated by scripts/generate.lua\n")
    out_file:write("return {\n")

    for _, glyph in ipairs(glyphs) do
        out_file:write(
            string.format('    { label = "%s", filterText="%s", insertText="%s", textEdit = { newText = "%s" } },\n',
                glyph.label,
                glyph.text_edit,
                glyph.text,
                glyph.text_edit
            )
        )
    end

    out_file:write("}\n")
    out_file:close()
end

download_file(url, tmp)

local glyphs = parse(tmp)

write_lua(glyphs, output_file)
print(string.format("Done. Written %d glyphs.", #glyphs))
